root = "."
tmp_dir = "tmp"

[build]
# コマンドの実行
cmd = "go build -o ./tmp/main ."
# バイナリファイル
bin = "./tmp/main"
# 監視対象の拡張子
include_ext = ["go", "tpl", "tmpl", "html", "env"]
# 除外するディレクトリ
exclude_dir = [".serena", "tmp", ".claude", "docs"]
# ファイル変更後の遅延時間
delay = 1000 # ms
# エラー時に停止
stop_on_error = true
# 割り込み信号を送信
send_interrupt = false
# プロセス終了までの待機時間
kill_delay = 500 # ms

[log]
time = true

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
# 終了時にtmpディレクトリを削除
clean_on_exit = true