services:
  tryon-app:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ${GOOGLE_APPLICATION_CREDENTIALS}:/app/credentials.json:ro
    restart: unless-stopped
    command: sleep infinity