version: '3.8'

services:
  tryon-app:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "8080:8080"
    environment:
      - PROJECT_ID=${PROJECT_ID}
      - LOCATION=${LOCATION:-us-central1}
      - VTO_MODEL=${VTO_MODEL:-virtual-try-on-preview-08-04}
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials.json
      - PORT=8080
    volumes:
      - ${GOOGLE_APPLICATION_CREDENTIALS}:/app/credentials.json:ro
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/healthz"]
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped

  # Optional: Add nginx as reverse proxy for production
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      # Uncomment for SSL certificates
      # - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - tryon-app
    restart: unless-stopped
    profiles:
      - production