FROM golang:1.24-alpine

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download && go install github.com/air-verse/air@latest

# 必要なディレクトリを作成
RUN mkdir -p /root/.config/gcloud

COPY . .

CMD ["air", "-c", ".air.toml"]
